# Generated by Django 5.1.4 on 2024-12-19 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.IntegerField(max_length=10, unique=True)),
                ('current_question', models.IntegerField(default=0)),
                ('correct', models.IntegerField(default=0)),
                ('answer_times', models.JSONField(default=list)),
                ('max_streak', models.IntegerField(default=0)),
                ('streak', models.IntegerField(default=0)),
            ],
        ),
    ]
