# Generated by Django 5.1.4 on 2024-12-19 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musiq', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesession',
            name='genre',
            field=models.CharField(default='All', max_length=100),
        ),
        migrations.AlterField(
            model_name='gamesession',
            name='session_id',
            field=models.IntegerField(unique=True),
        ),
    ]
