# Generated by Django 5.1.4 on 2024-12-27 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musiq', '0002_gamesession_genre_alter_gamesession_session_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
    ]
