# Generated by Django 5.1.4 on 2024-12-31 20:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musiq', '0005_account_last_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='first_login',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='account',
            name='username',
            field=models.CharField(max_length=10),
        ),
    ]
