# Generated by Django 5.1.4 on 2025-01-01 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musiq', '0006_account_first_login_alter_account_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='correct_musics',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='account',
            name='recent_score',
            field=models.FloatField(default=0),
        ),
    ]
