# Generated by Django 5.1.4 on 2025-01-02 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musiq', '0007_account_correct_musics_account_recent_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='userIcon',
            field=models.ImageField(default='static/media/default_icon.png', upload_to='user_icons/'),
        ),
    ]
