# Generated by Django 5.1.4 on 2025-01-02 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musiq', '0008_account_usericon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='userIcon',
            field=models.ImageField(blank=True, null=True, upload_to='user_icons/'),
        ),
    ]
