# Generated by Django 5.1.4 on 2025-01-02 17:28

import musiq.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musiq', '0009_alter_account_usericon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='userIcon',
            field=models.ImageField(blank=True, null=True, upload_to=musiq.models.user_icon_upload_to),
        ),
    ]
