# Generated by Django 5.1.4 on 2025-01-02 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musiq', '0011_alter_account_usericon'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='best_score',
            field=models.FloatField(default=0),
        ),
    ]
